name: Daily Commit Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action every day at midnight UTC
  push:
    branches:
      - main

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: 21f1006867@ds.study.iitm.ac.in
        uses: actions/checkout@v2

      # Create a commit
      - name: Create a daily commit (21f1006867@ds.study.iitm.ac.in)
        run: |
          echo "Updating repository with daily commit" >> update_log.txt
          git add update_log.txt
          git commit -m "Automated commit - $(date)"
          git push

      # Push using GitHub token for authentication
      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git push
