name: Daily Commit Workflow

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write permissions to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up the Git configuration
      - name: Set up Git identity
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # Create or modify a file (e.g., update_log.txt)
      - name: Create a daily commit file
        run: |
          echo "Automated daily commit - $(date)" >> update_log.txt

      # Commit and push the changes
      - name: Commit and push changes
        run: |
          git add update_log.txt
          git commit -m "Automated commit - $(date)" || exit 0
          git pull --rebase
          git push
